[package]
name = "war3-host-server"
version = "0.1.0"
edition = "2021"
authors = ["KouKouChan"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
rust-ini = "0.17"
