refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} - {m}{n}"
  file:
    kind: file
    path: "server.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
    - file